= Day 17: Trick Shot
:stem: latexmath
:page-stem: {stem}

link_day:17[] {link-sep} link_input:17[]

Holy crap.
This problem was _hard_.

[sidebar]
--
After looking at link:https://www.reddit.com/r/adventofcode/[the subreddit^] it looks like most people just brute forced it.
That's easy, but where's the fun in that?
Where possible, we want to solve these problems in the most computationally efficient manner possible.
--

We are asked to find the initial stem:[x]- and stem:[y]-velocities that will land a projectile, fired from the origin, in a given rectangular region stem:[R=[x_\mathrm{min}, x_\mathrm{max}\]\times[y_\mathrm{min}, y_\mathrm{max}\]].
In the stem:[x]-direction, the projectile suffers from drag, so its stem:[x]-velocity decreases by 1 each tick until it hits 0 (at which point it can't slow down anymore).
In the stem:[y]-direction, the projectile is affected by gravity (but no drag (?)), so its stem:[y]-velocity decreases by each tick, forever.

All numbers — time, positions, and velocities — must be (not-necessarily-positive) integers.
(And, naturally, time must be positive.)
This is an important and helpful constraint on the values we can use.

The solution below does not use brute force; it does not, for instance, try all stem:[v_x]s between 0 and stem:[R]'s right edge, or all stem:[v_y]s between stem:[-\mathrm{abs}(v_\mathrm{max})] and stem:[\mathrm{abs}(v_\mathrm{max})].
All potential times, positions, and speeds are derived mathematically.
It has no problem running on a target area of `x=1000000..1001000, y=-1000000..-1001000` (although this particular target area requires being able to take the integer square root of large numbers, which I did not implement myself).

***

== {setup-title}
--
include_source::mod.rs[tag=setup_main]
--

.The Math
Because stem:[x] decreases by 1 each tick until it hits 0, and stem:[y] decreases by 1 each tick forever, we have the following equations for the stem:[x]- and stem:[y]-coordinates at time stem:[t] of a projectile fired with an initial velocity of stem:[ (v_x, v_y)].
(Derivations are left to the reader, but a helpful fact is that stem:[1+2+\ldots+n = \frac{1}{2}n(n+1)].)

++++
\[
\begin{align*}
x(t, v_x) &=
\begin{cases}
v_x t - \frac{1}{2}t(t-1)&t \le v_x\\
\frac{1}{2}v_x(v_x+1)&t \ge v_x
\end{cases}\\
y(t, v_y)&=v_y t - \frac{1}{2}t(t-1)
\end{align*}
\]
++++

Note that even though the two definitions of stem:[x] overlap at stem:[t=v_x], they also coincide there, so it's not a problem.

Now, we must find the values of stem:[ (v_x,v_y)] that land the projectile in stem:[R].
To do this, we simply find the values of stem:[ (v_x,v_y)] that will land the projectile precisely at a point stem:[ (x,y)] in stem:[R], for each stem:[ (x,y)\in R].
And to do this, we find the stem:[ (v_x,v_y)] that will land the projectile at stem:[ (x,y)] precisely at time stem:[t], for each positive stem:[t].

To find the velocities that will land the projectile precisely at stem:[ (t,x,y)], we solve the above equations for stem:[v_x] and stem:[v_y].
Finding stem:[v_y] is simple: stem:[v_y=\frac{2y+t(t-1)}{2t}].
For stem:[v_x], it's a bit more complicated, as we have two options:
\[
v_x=\begin{cases}
\frac{2x+t(t-1)}{2t}&t\le v_x\\
\frac{-1\pm\sqrt{1+8x}}{2}&t\ge v_x
\end{cases}
\]

And as we said above, we need everything to be an integer, so we can either have no pairs of velocities that work, one pair, or two pairs.

include_source::mod.rs[tag=velo_finder]

Awesome.
We have the 0, 1, or 2 velocities that will land the projectile at stem:[ (x, y)] at time stem:[t].
But how to find the stem:[t]s for which the projectile can even land at stem:[ (x,y)]?
We cannot enumerate all stem:[t]s, as there are infinitely many positive integers.
Could we perhaps keep firing it with a larger and larger stem:[v_y] and hope that it would continue to land in stem:[R] at some point in its trajectory?
The answer is no: there are only finitely many values of stem:[v_y] for which there exists a time stem:[t] such that the projectile has a vertical position of stem:[y] at stem:[t].
Let's prove it, and let's find them.

Solving the equation stem:[y=v_y t- \frac{1}{2}t(t-1)] for stem:[t], we find that:
\[t=\frac{1}{2}\left((2v_y+1)\pm\sqrt{(2v_y+1)^2-8y}\right)\]
First and foremost, for this to be an integer, stem:[(2v_y+1)^2-8y] must be a perfect square.
Letting stem:[ m^2 =(2v_y+1) ^ 2] and stem:[n^2 = m^2 - 8y], we have stem:[m^2 - n^2 = 8y], which factors into stem:[(m-n)(m+n)=8y].
Since everything must be an integer, we can use the factor pairs of stem:[8y] to find stem:[m] and stem:[n].
If stem:[8y=(m-n)(m+n)=k_1k_2], then stem:[m=\frac{1}{2}(k_1+k_2)].
Hence, if stem:[2v_y+1=\frac{1}{2}(k_1+k_2)], then stem:[(2v_y+1)^2 - 8y] will indeed be a perfect square.
Of course, we also need stem:[\frac{1}{2}(k_1+k_2)] to be an odd integer so that stem:[v_y] will be an integer.
Finally, we plug stem:[v_y] into our equation for stem:[t] and if we get an integer, we've got a match: if the projectile is fired with a stem:[y]-velocity of stem:[v_y], then it will hit the vertical position stem:[y] precisely at stem:[t].

The astute reader will note that there _every_ projectile with stem:[v_y>0] hits stem:[y=0] on the way down.
Therefore we exclude stem:[y=0] from consideration altogether; a problem that included stem:[y=0] in stem:[R] would have infinitely many answers or be impossible to solve.

include_source::mod.rs[tag=time_finder]

We are nearly there!
To find whether, and how, the projectile can reach the point stem:[ (x,y)], we find:

. the set of pairs stem:[(t, v_y)] that give the projectile a vertical position of stem:[y] at time stem:[t], and
. for each of these pairs, we check that the projectile can indeed reach stem:[ (x,y)] at time stem:[t] (we know it can reach stem:[y], but can it reach stem:[x]?) and find the velocities stem:[ (v_x,v_y)] that will achieve that, if possible.

And we simply do this for every stem:[ (x,y)\in R].

include_source::mod.rs[tag=get_traj]

Once we get all the trajectories, the actual answers we're asked for are pretty simple.

== {part-title} 1
Part 1 asks us to find the maximum possible height that can be achieved by a projectile that reaches stem:[R].
As we said above, a projectile with initial stem:[y]-velocity stem:[v_y] reaches an apex of stem:[\frac{1}{2}v_y(v_y+1)].

include_source::mod.rs[tag=pt1]

== {part-title} 2
Part 2 asks us to simply count distinct initial velocities that land the projectile in stem:[R].

include_source::mod.rs[tag=pt2]
