= Day 5: Hydrothermal Venture
:stem: latexmath
:page-stem: {stem}

link_day:5[] {link-sep} link_input:5[]

This challenge requires iterating the integer points between two other points on the plane.

***

== {setup-title}
First, we read the input into a list of lines of the form stem:[((x_1, y_1), (x_2, y_2))].
We also define the helpful `range_between(a, b)` function, which returns the (nonempty!) range of integers between `a` and `b`, inclusive.
The range is ascending if and only if `a < b`.
(This is different from `a..=b`, which is empty if `a > b`.)

include_source::mod.rs[tag=setup]

== {part-title} 1
Part 1 asks us to count how many times each point belongs to some horizontal or vertical line.
These are lines stem:[((x_1, y_1), (x_2, y_2))] for which stem:[x_1 = x_2] or stem:[y_1 = y_2].
Such a line's points are the Cartesian “product” of the ranges `range_between(x1, x2)` and `range_between(y1, y2)` (“product” in quotes because one of those ranges has length 1, so it's not much of a product).

include_source::mod.rs[tag=pt1]

== {part-title} 2
Part 2 asks us to count how many times each point belongs to either a horizontal line, a vertical line, or a stem:[45^\circ] diagonal line (whose slope must be stem:[\pm1]).
We already found the points on horizontal and vertical lines in {part-title} 1.
Diagonal lines are lines stem:[((x_1, y_1), (x_2, y_2))] whose points stem:[ (x_k,y_k)] satisfy stem:[|x_k-x_1|=|y_k-y_1|] with stem:[x_k] between stem:[x_1] and stem:[x_2] and stem:[y_k] between stem:[y_k] and stem:[y_2] (inclusive).
Since the stem:[k]^th^ element of `range_between(a, b)` is stem:[k] away from stem:[a], the points of the diagonal line in question are in fact simply the elements of `range_between(x1, x2).zip(range_between(y1, y2))`.

include_source::mod.rs[tag=pt2]
