always_for_in = false
always_use_return = true
conditional_to_if = true
format_docstrings = true
pipe_to_function_call = false
remove_extra_newlines = true
short_to_long_function_def = false
style = "blue"
whitespace_ops_in_indices = true
