site:
  robots: allow
  title: Advent of Code 2021
  url: /

content:
  sources:
    - url: ./solutions
      branches: HEAD

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://github.com/rben01/antora-ui/releases/latest/download/ui-bundle.zip
    url: ~/Documents/CloudDocs/Documents/Coding/Projects/Antora Theme/src

urls:
  html_extension_style: drop

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  attributes:
    hide-uri-scheme: true
    click-to-reveal: Click to reveal answer
    caution-caption: true
    soln-description-title: Description of Solution
    setup-title: Setup
    part-title: Part
    page-pagination: true
