[package]
	edition = "2021"
	name = "advent_of_code_2021"
	version = "0.1.0"

	# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
	ndarray = "0.15.4"
	num = "0.4.0"
