= Day 1

// tag::content[]

:day-num: 1
{external-link-left-delim}link:{advent-day-url-stem}{day-num}[{external-link}]{external-link-right-delim}

.{soln-description-texternal-link}
Problem 1 asks to find when the current depth is greater than the previous depth.
Problem 2 asks to find when the current running sum of depths is greater than the previous running sum (with a running sum of length 3, but no need to bake that in just yet).
Problem 1 is a special case of Problem 2, with a running sum length of \(n=1\).

The solution uses a https://juliacollections.github.io/DataStructures.jl/latest/circ_buffer/[`CircularBuffer`^] (c.f. https://en.wikipedia.org/wiki/Circular_buffer) to keep the past \(n\) depths.
Since the “interior” components of the current and previous running sums are the same, we can compare the two running sums by merely checking the new depth against the oldest depth still in the buffer.
If the current depth is greater, then so is the current running sum.

.Setup
[source,julia,indent=0]
----
include::./soln.jl[tag=setup,indent=3]
----

.{part-title} 1
[source,julia,indent=0]
----
include::./soln.jl[tag=pt1,indent=3]
----
.{click-to-reveal}

.{part-title} 2
[source,julia,indent=0]
----
include::./soln.jl[tag=pt2,indent=3]
----

// end::content[]
