= Day 3: Binary Diagnostic
:stem: latexmath
:page-stem: {stem}

link_day:3[] {link-sep} link_input:3[]

This challenge mostly just requires filtering arrays and counting elements satisfying a condition.

***

== {setup-title}
The first thing we do is read the input file into a `ndarray::Array2<bool>` of size `(n_rows, n_cols)`, where a `true` value corresponds to a `1` character in the input, and a `false` to a `0`.
We also created a function that converts a binary vector, most significant digit first, to a (decimal) number (see the link:../advent_of_code_2021.html#_setup[Setup] section).
For example, given `10011`, we compute `[1, 0, 0, 1, 1] .* [16, 8, 4, 2, 1] = [16, 0, 0, 2, 1]`, whose sum is 19.
(This is just how link:https://en.wikipedia.org/wiki/Positional_notation#Mathematics[positional notation^] works.)

include_source::mod.rs[tag=setup]

== {part-title} 1

We are asked to find two numbers, `gamma_rate` (stem:[\gamma]) and `epsilon_rate` (stem:[\varepsilon]).
stem:[\gamma] is the value of the binary number whose stem:[k]^th^ digit is the most common digit in column stem:[k] of the array of values.
stem:[\varepsilon] is computed using the same idea, but with the least common digit instead.
(It is assumed that there will be no ties.)

Since there are only two digits to choose from, the most common digit and the least common digit in each column will be opposites, and so stem:[\gamma + \varepsilon = \text{all 1s} = 2^{\text{\texttt{line\textunderscore{}width}}}-1].
In other words we don't need to compute stem:[\varepsilon] “the long way”; once we have stem:[\gamma], we immediately have stem:[\varepsilon].

include_source::mod.rs[tag=pt1]

== {part-title} 2

We are asked to find two new numbers, the oxygen scrubber rating `oxy_rate` and the CO2 scrubber rating `co2_rate`.
The procedure to find the `oxy_rate` is as follows: +

. Initialize the list of candidate values to the full list of rows in `elems` as defined above.
. With stem:[k] ranging from the leftmost column index in `elems` to the rightmost column index (most significant digit to least):
.. Successively narrow down the list of candidates by keeping only those remaining candidates whose stem:[k]^th^ digit is the most common stem:[k]^th^ digit of the remaining candidates, with a tie between 0 and 1 going to 1.
*** For instance, when stem:[k=5], then keep only the remaining candidates whose 5^th^ digit is the most common 5^th^ digit (0 or 1, ties going to 1) of all remaining candidates at that stage.
.. Stop when only one candidate remains.
(This is guaranteed to happen as long as the rows are all distinct.)

The procedure for `co2_rate` is the same, except that the list of candidates is filtered down according to the _least_ common digit in each position, with ties going to 0.

include_source::mod.rs[tag=pt2]
