= Advent of Code 2021
include::./docs/shared.adoc[]
:toc: left
:toc-title: Contents
:toclevels: 1
:!sectnums:
:sectnumlevels: 1
:sectanchors:
:src-dir: src

[.lead]
This doc has my solutions for the https://adventofcode.com/2021[2021 Advent of Code^].
It assumes some familiarity with https://www.rust-lang.org/[the Rust language^].

[NOTE]
====
Advent of Code gives all participants the same problems, but gives different inputs to each participant.
Therefore, it makes little sense to give the actual numeric answers to problems here.
However, we do provide the input that was given to us in order to contextualize the input-parsing code.
The solutions below should work for any input/output pair provided by Advent of Code.
====

[WARNING]
====
This document has the solutions out in the open!
Don't read it if you're still working on Advent of Code.
====


== Setup
Rust is a very strict language and makes you explicitly handle all errors that might arise (as opposed to, say,  exceptions implicitly being thrown on error, as Python does).
However, we can trust our inputs, taken straight from Advent of Code, to be correct and give unambiguous answers without errors.
For this reason, we tend to be pretty loosey-goosey about unwrapping the ``Option``s and ``Result``s that the Rust compiler correctly points out we could theoretically encounter.
(There wouldn't be any point to handling those cases gracefully; we're just trying to solve Advent of Code, not create general-purpose a submarine-squid-bingo-player that can function sensibly even when the squid gives us nonsensical input.
For our purposes, the residual variants of a `Try` object at the boundary of our program are `!` (Rust's bottom or “never” type).)


Commonly used code, in `src/lib.rs` and `src/utils.rs`, is below:

.link:../{src-dir}/lib.rs[`lib.rs`^]
--
include_source::{src-dir}/lib.rs[tag=!mods]
--

.link:../{src-dir}/utils.rs[`utils.rs`^]
--
include_source::{src-dir}/utils.rs[tag=code]
--


== Problems and Solutions

. link:day_adocs/day_01.html[Day 1]
. link:day_adocs/day_02.html[Day 2]
. link:day_adocs/day_03.html[Day 3]
. link:day_adocs/day_04.html[Day 4]
. link:day_adocs/day_05.html[Day 5]
. link:day_adocs/day_06.html[Day 6]
. link:day_adocs/day_07.html[Day 7]
. link:day_adocs/day_08.html[Day 8]
. link:day_adocs/day_09.html[Day 9]
. link:day_adocs/day_10.html[Day 10]
. link:day_adocs/day_11.html[Day 11]
. link:day_adocs/day_12.html[Day 12]
. link:day_adocs/day_13.html[Day 13]
. link:day_adocs/day_14.html[Day 14]
. link:day_adocs/day_15.html[Day 15]
. link:day_adocs/day_16.html[Day 16]
. link:day_adocs/day_17.html[Day 17]
. link:day_adocs/day_18.html[Day 18]
. link:day_adocs/day_19.html[Day 19]
. link:day_adocs/day_20.html[Day 20]
. link:day_adocs/day_21.html[Day 21]
. link:day_adocs/day_22.html[Day 22]
. link:day_adocs/day_23.html[Day 23]
. link:day_adocs/day_24.html[Day 24]
. link:day_adocs/day_25.html[Day 25]


== Conclusion

This was a lot of work, but a lot of fun, and I learned a ton, both about algorithms in general and about Rust.
Looking forward to next year's Advent of Code!
