= Advent of Code 2021
:docinfodir: ./Docs
:docinfo: shared
:stylesheet: /Docs/aoc.css
:linkcss:
:nofooter:
:toc: left
:toc-title: Challenges
:toclevels: 1
:sectnums:
:sectnumlevels: 1
:sectanchors:
:source-highlighter: pygments
:pygments-style: default
:pygments-linenums-mode: table
:src-dir: src
:icons: font
:link-sep: │
:click-to-reveal: Click to reveal answer
:caution-caption:
:soln-description-title: Description of Solution
:setup-title: Setup
:part-title: Part
:hide-uri-scheme:

[.lead]
This doc has my solutions for the https://adventofcode.com/2021[2021 Advent of Code^].
It assumes some familiarity with https://www.rust-lang.org/[the Rust language^].

[NOTE]
====
Advent of Code gives all participants the same problems, but gives different inputs to each participant.
Therefore, it makes little sense to give the actual numeric answers to problems here.
However, we do provide the input that was given to us in order to contextualize the input-parsing code.
The solutions below should work for any input/output pair provided by Advent of Code.
====

[WARNING]
====
This document has the solutions out in the open!
Don't read it if you're still working on Advent of Code.
====

:!sectnums:

== Setup
Rust is a very strict language and makes you explicitly handle all errors that might arise (as opposed to, say,  exceptions implicitly being thrown on error, as Python does).
However, we can trust our inputs, taken straight from Advent of Code, to be correct and give unambiguous answers without errors.
For this reason, we tend to be pretty loosey-goosey about unwrapping the ``Option``s and ``Result``s that the Rust compiler correctly points out we could theoretically encounter.
(There wouldn't be any point to handling those cases gracefully; we're just trying to solve Advent of Code, not create general-purpose a submarine-squid-bingo-player that can function sensibly even when the squid gives us nonsensical input.
For our purposes, the residual variants of a `Try` object at the boundary of our program are `unreachable!()`.)


Commonly used code, in `src/lib.rs` and `src/utils.rs`, is below:

.link:/src/lib.rs[`lib.rs`^]
--
include_source::{src-dir}/lib.rs[tag=!mods]
--

.link:/src/utils.rs[`utils.rs`^]
--
include_source::{src-dir}/utils.rs[tag=code]
--


:sectnums:

include::{src-dir}/day_01/soln.adoc[leveloffset=+1]

include::{src-dir}/day_02/soln.adoc[leveloffset=+1]

include::{src-dir}/day_03/soln.adoc[leveloffset=+1]

include::{src-dir}/day_04/soln.adoc[leveloffset=+1]

include::{src-dir}/day_05/soln.adoc[leveloffset=+1]

include::{src-dir}/day_06/soln.adoc[leveloffset=+1]

include::{src-dir}/day_07/soln.adoc[leveloffset=+1]

include::{src-dir}/day_08/soln.adoc[leveloffset=+1]

include::{src-dir}/day_09/soln.adoc[leveloffset=+1]

include::{src-dir}/day_10/soln.adoc[leveloffset=+1]

include::{src-dir}/day_11/soln.adoc[leveloffset=+1]

include::{src-dir}/day_12/soln.adoc[leveloffset=+1]

include::{src-dir}/day_13/soln.adoc[leveloffset=+1]

include::{src-dir}/day_14/soln.adoc[leveloffset=+1]

include::{src-dir}/day_15/soln.adoc[leveloffset=+1]

include::{src-dir}/day_16/soln.adoc[leveloffset=+1]

include::{src-dir}/day_17/soln.adoc[leveloffset=+1]

include::{src-dir}/day_18/soln.adoc[leveloffset=+1]

include::{src-dir}/day_19/soln.adoc[leveloffset=+1]

include::{src-dir}/day_20/soln.adoc[leveloffset=+1]
